name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20.10.0' }
      - run: npm ci
      - run: npm run build
      - run: npx http-server dist -p 4321 & sleep 2
      - run: PREVIEW_URL="http://127.0.0.1:4321" npm run test:smoke
